"""Interactive script to visually check nearest-neighbour data against
the real LED display.

Lights up one LED at a time in white, together with its 6 nearest
neighbours (loaded from the CSV files below) in red, so you can step
through the array and check by eye whether the listed neighbours are
actually next to the lit LED.

The neighbour data is loaded from:
    src/display1593/data/nearest_neighbours_1593.csv
    src/display1593/data/nearest_neighbour_distances_1593.csv
which were (re)generated by compute_nearest_neighbours() in
ledArray_data_1593.py using a periodic (wrap-around) KDTree.

Controls (single keypress, no Enter needed except when typing a LED
number to jump to):
    n, <space>, <Enter> - go to the next LED
    b                   - go back to the previous LED
    <digits><Enter>     - jump directly to that LED id
    q                   - quit
"""

import sys
import termios
import tty
from pathlib import Path

import numpy as np

from display1593 import Display1593
from display1593 import data as data_pkg
from display1593.data.ledArray_data_1593 import num_cells

DATA_DIR = Path(data_pkg.__file__).parent
NEIGHBOURS_CSV = DATA_DIR / "nearest_neighbours_1593.csv"

CENTRE_COLOUR = (32, 32, 32)  # white
NEIGHBOUR_COLOUR = (32, 0, 0)  # red


def load_nearest_neighbours():
    return np.loadtxt(NEIGHBOURS_CSV, delimiter=",", dtype=int)


def getch():
    """Read a single keypress from stdin without waiting for Enter."""
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setcbreak(fd)
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    return ch


def read_led_id():
    """Read digits (with backspace support) until Enter, and return the
    LED id typed, or None if nothing usable was entered."""
    digits = ""
    while True:
        ch = getch()
        if ch in ("\r", "\n"):
            break
        elif ch == "\x7f":  # backspace
            if digits:
                digits = digits[:-1]
                sys.stdout.write("\b \b")
                sys.stdout.flush()
        elif ch.isdigit():
            digits += ch
            sys.stdout.write(ch)
            sys.stdout.flush()
    print()
    return int(digits) if digits else None


def show_led_and_neighbours(dis, nearest_neighbours, led_id):
    neighbours = nearest_neighbours[led_id]
    dis.clear_all()
    dis.set_leds_one_colour(neighbours, NEIGHBOUR_COLOUR)
    dis.set_led(led_id, CENTRE_COLOUR)
    dis.show_now()
    print(f"LED {led_id} (white), neighbours {neighbours.tolist()} (red)")


def main():
    nearest_neighbours = load_nearest_neighbours()
    print(__doc__)

    with Display1593() as dis:
        led_id = 0
        show_led_and_neighbours(dis, nearest_neighbours, led_id)
        while True:
            print(f"[led {led_id}] > ", end="", flush=True)
            ch = getch()
            if ch == "q":
                print()
                break
            elif ch in ("n", " ", "\r", "\n"):
                print()
                led_id = (led_id + 1) % num_cells
            elif ch == "b":
                print()
                led_id = (led_id - 1) % num_cells
            elif ch.isdigit():
                print(ch, end="", flush=True)
                rest = read_led_id()
                new_id = int(ch + str(rest)) if rest is not None else int(ch)
                if 0 <= new_id < num_cells:
                    led_id = new_id
                else:
                    print(f"Out of range (0-{num_cells - 1})")
                    continue
            else:
                print(f"\nUnrecognized key {ch!r}. Use n/space/Enter, 'b', a number, or 'q'.")
                continue
            show_led_and_neighbours(dis, nearest_neighbours, led_id)

        dis.clear_all()
        dis.show_now()


if __name__ == "__main__":
    main()
