"""Interactive script to visually check nearest-neighbour data against
the real LED display.

Lights up one LED at a time in white, together with its 6 nearest
neighbours in red, so you can step through the array and check by eye
whether the listed neighbours are actually next to the lit LED.

The neighbour data is read from the Display1593 object (dis.leds),
which loads it from the corrected CSV files:
    src/display1593/data/nearest_neighbours_1593.csv
    src/display1593/data/nearest_neighbour_distances_1593.csv
(see display1593.py). These were (re)generated by
compute_nearest_neighbours() in ledArray_data_1593.py using a periodic
(wrap-around) KDTree.

Controls (single keypress, no Enter needed except when typing a LED
number to jump to):
    n, <space>, <Enter> - go to the next LED
    b                   - go back to the previous LED
    <digits><Enter>     - jump directly to that LED id
    q                   - quit
"""

import sys
import termios
import tty

from display1593 import Display1593

CENTRE_COLOUR = (32, 32, 32)  # white
NEIGHBOUR_COLOUR = (32, 0, 0)  # red


def getch():
    """Read a single keypress from stdin without waiting for Enter."""
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setcbreak(fd)
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    return ch


def read_led_id():
    """Read digits (with backspace support) until Enter, and return the
    LED id typed, or None if nothing usable was entered."""
    digits = ""
    while True:
        ch = getch()
        if ch in ("\r", "\n"):
            break
        elif ch == "\x7f":  # backspace
            if digits:
                digits = digits[:-1]
                sys.stdout.write("\b \b")
                sys.stdout.flush()
        elif ch.isdigit():
            digits += ch
            sys.stdout.write(ch)
            sys.stdout.flush()
    print()
    return int(digits) if digits else None


def show_led_and_neighbours(dis, nearest_neighbours, led_id):
    neighbours = nearest_neighbours[led_id]
    dis.clear_all()
    dis.set_leds_one_colour(neighbours, NEIGHBOUR_COLOUR)
    # Note: set_led() (the "L1" command) appears not to light LEDs on the
    # second Teensy board (ids >= 798) - use set_leds_one_colour() for the
    # centre LED too since that command path works on both boards.
    dis.set_leds_one_colour([led_id], CENTRE_COLOUR)
    dis.show_now()
    print(f"LED {led_id} (white), neighbours {neighbours.tolist()} (red)")


def main():
    print(__doc__)

    with Display1593() as dis:
        nearest_neighbours = dis.leds.nearest_neighbours
        num_cells = dis.leds.num_cells

        led_id = 0
        show_led_and_neighbours(dis, nearest_neighbours, led_id)
        while True:
            print(f"[led {led_id}] > ", end="", flush=True)
            ch = getch()
            if ch == "q":
                print()
                break
            elif ch in ("n", " ", "\r", "\n"):
                print()
                led_id = (led_id + 1) % num_cells
            elif ch == "b":
                print()
                led_id = (led_id - 1) % num_cells
            elif ch.isdigit():
                print(ch, end="", flush=True)
                rest = read_led_id()
                new_id = int(ch + str(rest)) if rest is not None else int(ch)
                if 0 <= new_id < num_cells:
                    led_id = new_id
                else:
                    print(f"Out of range (0-{num_cells - 1})")
                    continue
            else:
                print(
                    f"\nUnrecognized key {ch!r}. Use n/space/Enter, 'b', a number, or 'q'."
                )
                continue
            show_led_and_neighbours(dis, nearest_neighbours, led_id)

        dis.clear_all()
        dis.show_now()


if __name__ == "__main__":
    main()
